### ISSUE TITLE
Add `Wireless Debugging` tile also

### ISSUE THREAD

**Issue by vippium** [louie-velarde/DevQS#3]
Can you also add the `Wireless Debugging tile` also, as some apps need dev. options to be turned off. And after turning off the D.O., the wireless debugging tile removed. As the tile option from dev. options need dev. options to be turned on all time to access tiles. 

It will be helpful for users who use shizuku and apps time-to-time.
Just add that one tile also.

**Comment by louie-velarde** [comment]
Please check the new version (1.1.0) that is now available on F-Droid.

**Comment by vippium** [comment]
> Please check the new version (1.1.0) that is now available on F-Droid.

Thanks for Listening... Closing Now
