### ISSUE TITLE
Tiles on the quick settings panel are disabled

### ISSUE THREAD

**Issue by Radoq10288** [louie-velarde/DevQS#4]
Upon installing DevQS and adding the 'dev', 'adb', and 'wireless adb' tiles in my phone's quick settings panel, the three tiles are disabled even after granting the 'WRITE_SECURE_SETTINGS'.

By the way, I'm using Android 12.

**Comment by louie-velarde** [comment]
Is the device unlocked? The tiles are disabled on the lock screen.

**Comment by Radoq10288** [comment]
Even if it's unlocked, the tiles are still disabled. I also tried turning off the 'developers option' but it was still the same.

**Comment by louie-velarde** [comment]
Do you mean it still says "Unavailable" even after unlocking the device?
![Screenshot_20240930_165638](https://github.com/user-attachments/assets/5895c414-1ab7-45bd-8c2f-b56d5ef77111)


What launcher / home screen app are you using? Have you tried other launcher / home screen apps?

**Comment by Radoq10288** [comment]
It doesn't say 'Unavailable', it's just disabled.
![Uploading Screenshot_20240930-175141.jpg…]()

**Comment by Radoq10288** [comment]
It doesn't say 'Unavailable', it is just disabled for some reason. I even changed to my default launcher.
![Screenshot_20240930-175141](https://github.com/user-attachments/assets/07f47862-e6d3-4a3c-a081-4746bf697a1d)

**Comment by louie-velarde** [comment]
Do you by any chance use a device from one of the manufacturers listed in [dontkillmyapp.com](https://dontkillmyapp.com)? Have you tried allowing auto-start / turning off "optimizations" for the app?

**Comment by Radoq10288** [comment]
My device doesn't belong to the list of phone manufacturers indicated on the site but I tried enabling it in the auto-start, and it worked!!!

Thank you so much for the help and sorry for the trouble...
