### ISSUE TITLE
Add `Private dns` button with 3 taps

### ISSUE THREAD

**Issue by vippium** [louie-velarde/DevQS#5]
This is also a useful tile as this tile will allow users to directly enable/disable the private dns from the QS. If user is using some custom dns like adguard dns, then he need to turn off/automatic the private dns to use some sites which actually doesn't allow adblockers. This QS will make the work easier for the user and end the efforts of going into settings and sub settings.
The three tap will work like that:
1. First Tap - OFF
2. Second Tap - Automatic
3. Third Tap - Custom DNS

I know that this is not the Dev. Options feature. But it is a useful feature as no one provide this.

**Comment by louie-velarde** [comment]
I don't use AdGuard DNS but it seems one can unblock a domain.
https://adguard-dns.io/kb/general/dns-filtering-syntax/#basic-examples

**Comment by vippium** [comment]
> I don't use AdGuard DNS but it seems one can unblock a domain. https://adguard-dns.io/kb/general/dns-filtering-syntax/#basic-examples

It can... But unblocking so many domain is not worth. Like downloading mods require disabling adblocker. As they use shortners for their earning. That's the reason for that. I already tried ur suggestion.

**Comment by vippium** [comment]
`Private DNS Android` does the same work as I requested here. Just the change in that is it is a app in which we can add more than one DNS servers and switch b/w them.

If you are working on this tile, just add only those three toggles. You can just skip the OFF toggle and remain with two tap toggles.

**Comment by vippium** [comment]
If you are not working on this tile, then simply close the issue with `Not Planned Yet` tag.
